
const roadsSection = [
  {
    id: "roads_items",
    caretId: "roads-layer-caret",
    label: "Roads",
    itemSelector: ".roads_layer_item",
    zoomTo: "World",
    infoId: "roads-info-layer",
    type: "group",
    collapsed: false,
	checked: true,
  },
  {
    id: "confirmed-roads",
    name: "confirmed-roads",
    label: "Confirmed",
    iconColor: "#A9A9A9",
    className: "roads_layer",
    topLayerClass: "roads_layer",
    isSolid: true,
    iconType: "slash",
    checked: true,
  },
  {
    id: "sub-roads",
    name: "sub-roads",
    label: "Subdivision Roads",
    iconColor: "#808080",
    className: "roads_layer",
    topLayerClass: "roads_layer",
    isSolid: true,
    iconType: "slash",
    checked: true,
  },
  {
    id: "proxy-roads",
    name: "proxy-roads",
    label: "Proximity",
    iconColor: "#696969",
    className: "roads_layer",
    topLayerClass: "roads_layer",
    isSolid: true,
    iconType: "slash",
    checked: true,
  }
];


const buildingsSection = [
  {
    id: "builds_items",
    caretId: "builds-layer-caret",
    label: "Buildings",
    itemSelector: ".builds_layer_item",
    zoomTo: "World", // Update zoom logic if needed
    infoId: "builds-info-layer",
    type: "group",
    collapsed: false,
	checked: true,
  },
  {
    id: "prev-builds",
    name: "prev-builds",
    label: "Previous buildings",
    iconColor: "#FF7F50",
    className: "builds_layer",
    topLayerClass: "builds_layer",
    isSolid: true,
    iconType: "square",
    checked: true,
  },
  {
    id: "curr-builds",
    name: "curr-builds",
    label: "Current buildings",
    iconColor: "#35b779",
    className: "builds_layer",
    topLayerClass: "builds_layer",
    isSolid: true,
    iconType: "square",
    checked: true,
  }
];

const parcelsSection = [
  {
    id: "parcels_items",
    caretId: "parcels-layer-caret",
    label: "Parcels",
    itemSelector: ".parcels_layer_item",
    zoomTo: "World",
    infoId: "parcels-info-layer",
    type: "group",
    collapsed: true,
	checked: false,
  },
  {
    id: "lot-lines",
    name: "lot-lines",
    label: "Lot Lines",
    iconColor: "#ffd700",
    className: "parcels_layer",
    topLayerClass: "parcels_layer",
    isSolid: false,
    iconType: "square",
    checked: false,
  },
  {
    id: "parcels-parcels",
    name: "parcels-parcels",
    label: "Parcels",
    iconColor: "#ff1493",
    className: "parcels_layer",
    topLayerClass: "parcels_layer",
    isSolid: true,
    iconType: "square",
    checked: false,
  },
  {
    id: "parcels-subs",
    name: "parcels-subs",
    label: "Subdivisions",
    iconColor: "#7b68ee",
    className: "parcels_layer",
    topLayerClass: "parcels_layer",
    isSolid: true,
    iconType: "square",
    checked: false,
  }
];

const parcelsPLSSsection = [
  {
    id: "plss_parcels_items",
    caretId: "plss-parcels-layer-caret",
    label: "PLSS Parcels",
    itemSelector: ".plss_parcels_layer_item",
    zoomTo: "World",
    infoId: "plss-parcels-info-layer",
    type: "group",
    collapsed: true,
	checked: false,
  },
  {
    id: "plss-own",
    name: "plss-own",
    label: "PLSS Ownership",
    iconColor: "#00E5D9",
	className: "plss_parcels_layer",
    topLayerClass: "plss_parcels_layer",
    isSolid: true,
    iconType: "square",
    checked: false,
  },
  {
    id: "plss-parcels",
    name: "plss-parcels",
    label: "PLSS Parcels",
    iconColor: "#00ff7f",
	className: "plss_parcels_layer",
    topLayerClass: "plss_parcels_layer",
    isSolid: true,
    iconType: "square",
    checked: false,
  },
  {
    id: "land-patents",
    name: "land-patents",
    label: "Story County Land Patents",
    iconColor: "#e3ed58",
	className: "plss_parcels_layer",
    topLayerClass: "plss_parcels_layer",
    isSolid: true,
    iconType: "square",
    checked: false,
  }
];

const singleLayers = [
  {
    id: "rail-roads",
    name: "rail-roads",
    label: "Railroads",
    iconColor: "#ff0000",
    className: "rail_roads_layer",
    topLayerClass: "rail_roads_layer",
    isSolid: true,
    iconType: "slash",
    checked: true,
    containerId: "rail-roads-cont",
	zoomTo: "World",
    infoId: "rail-roads-info-layer",
  },
  {
    id: "city-limits",
    name: "city-limits",
    label: "City Limits",
    iconColor: "#6495ED",
    className: "city_limits_layer",
    topLayerClass: "city_limits_layer",
    isSolid: true,
    iconType: "square",
    checked: true,
    containerId: "city-limits-cont",
	zoomTo: "World",
    infoId: "city-limits-info-layer",
  }
];


